name: Release
run-name: build and push docker image as latest to hub.docker.com/r/matteoschmider/winget as latest
#on:
#  release:
#    types: [created, edited]
on:
  push

jobs:
  Build-Push-Image:
    runs-on: windows-2022
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          registry: docker.io
          image: matteoschmider/winget
          tags: latest, ${{ github.ref_name }}
          dockerfile: winget.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
