name: Release
run-name: build and push docker image as latest to hub.docker.com/r/matteoschmider/winget as latest
on:
  push
#  release:
#    types: [created, edited]

jobs:
  Build-Push-Image:
    runs-on: windows-latest
    container:
      image: mcr.microsoft.com/windows:ltsc2022

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: dir