name: Release
run-name: build and push docker image as latest to hub.docker.com/r/matteoschmider/winget as latest
on:
  push
#  release:
#    types: [created, edited]

jobs:
  Build-Push-Image:
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: winget.Dockerfile
          push: true
          tags: matteoschmider/winget:latest
